### ISSUE TITLE
Control Rods not functioning properly

### ISSUE THREAD

**Issue by FroZtyFire** [Kasra-G/ReactorController#10]
When I boot up the reactor in Extreme reactors it jumps quickly between full control and nothing or 100% and 0% instead of calculating a value between 100 and 0. I don't know if this effects it at all, but I have a 11x5x11 Reactor with a 3x3x3 control rod core with a max of 11.67 MFE. If you would be willing to help me that would be great

**Comment by Kasra-G** [comment]
Over time the reactor should stabilize, assuming you draw less power than the reactor produces. To speed it up, you can try setting the buffer % minimum to 0 and the maximum to 100. It might fluctuate between 0 and 100 as the internal reactor buffer fills. This should fix itself over time. Then once the control rods have stabilized you can set the buffer % min/max to whatever. 

I think this is ultimately due to the fact that upon startup, the control rods are all set to 0 before increasing. A better approach would be to set them to 100 and slowly let down until the reactor buffer is power positive.

Let me know how it goes

**Comment by FroZtyFire** [comment]
Awesome! Thanks and I will definitely will let you know how if goes

**Comment by FroZtyFire** [comment]
So it still periodically jumps to 0% control when below the cap which causes a spike in power which in turn pushes the value out of bounds. This is not a problem technically, but I think it would be cool if if the reactor tried to hover between the two values that one selects.

**Comment by Kasra-G** [comment]
The program is supposed to, however it looks like when the reactor's power drain is small compared to the amount it can generate, the program has trouble keeping the power level in between the selected buffer range. Usually this can be worked around by giving a wider buffer range, but its not perfect. Sorry about the problems, but if it is any consolation, when you expand your base and draw more power out of the reactor, it should handle better.

**Comment by Kasra-G** [comment]
Been a while, but im working on an update that changes how the control rods are controlled. This should help with this. I'm thinking of adding turbine support soon after as well
