### ISSUE TITLE
Incorrect temperature units displayed (C instead of K)

### ISSUE THREAD

**Issue by heimskr** [Kasra-G/ReactorController#13]
I'm using this script (works great, btw—thanks for making it!) with Bigger Reactors and noticed that the temperature units displayed by this script (Celsius) aren't the same as the units displayed by the reactor terminal's UI (Kelvin). My speculation is that perhaps reactor mods prior to Bigger Reactors used Celsius and that Bigger Reactors switched to Kelvin. It's been a while since I've played with reactor mods prior to Bigger Reactors so I could definitely be wrong about that.

Here are some screenshots in case they're helpful:

![Celsius displayed by script](https://github.com/Kasra-G/ReactorController/assets/13513421/1db3f00f-2bed-47c4-8f17-86a1ab974ee1)

![Kelvin displayed by Bigger Reactors UI](https://github.com/Kasra-G/ReactorController/assets/13513421/35e75dd4-318a-4abd-ab73-0c6618f19972)

**Comment by Kasra-G** [comment]
Hey! This is probably something i overlooked when adding support for other reactor mods. It was initially tested for Extreme Reactors. I'm currently working on an update that makes the control rod algorithm more inline with realworld applications (PID controller). I'll go ahead and throw the fix for this in with that update

**Comment by Kasra-G** [comment]
Should be fixed, next time your advanced computer restarts, it will grab the latest update
