### ISSUE TITLE
Possibility for control rod insertion management?

### ISSUE THREAD

**Issue by dumptruckfabio** [Kasra-G/ReactorController#8]
Any chance we could get an update that adds a UI option allowing us to modify control rod insertion to better manage heat levels and efficiency for fuels other than yellorium? running a blutonium reactor basically instantly jumps the heat to 2200~ and creates fuel inefficiency

**Comment by Kasra-G** [comment]
I suppose I never tested the controller on anything other than yellorium reactors. Does it remain inefficient after the internal buffers have reached the desired fill range? The control rods are controlled by the reactor's energy buffer, so if the energy buffer is below the minimum fill % it will set the control rods to 0 to attempt to fill up the buffer. I could add a toggle button to switch between automatic and manual control rod insertion. This would allow you to globally change control rod insertion levels (with minimum 1% increment) though ideally there'd be a menu system where you could individually/collectively set control rods - this would have to come later.

**Comment by Kasra-G** [comment]
Looking into making a different start sequence so that the control rods start fully inserted and slowly let back. Will be slower to start but is more fuel efficient. I really need to change the math of the reactor to be a PID controller. Something for the future, I guess.

**Comment by Kasra-G** [comment]
Ideally the need for this has been somewhat mitigated with the change to use a PID controller last year. The goal of the program is so that you _don't_ have to manage the rods manually, and I'm not sure how to make the UI for that fit. If you want fine-grained access to the control rod levels, try this script https://gitlab.com/seekerscomputercraft/extremereactorcontrol/ - it's a more complicated UI but it allows for much more configuration/control

Because of that I'm removing the enhancement label and labeling as not planned.
